// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQ0EZXBNVtoTNlkTQgUs7sOUYtdeTdGA',
    appId: '1:322047224635:web:16d105e8b9b35a62d2e51e',
    messagingSenderId: '322047224635',
    projectId: 'flutter-ui-challenges-hgl',
    authDomain: 'flutter-ui-challenges-hgl.firebaseapp.com',
    databaseURL: 'https://flutter-ui-challenges-hgl.firebaseio.com',
    storageBucket: 'flutter-ui-challenges-hgl.appspot.com',
    measurementId: 'G-HS61TMQ4DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9j1uxAdRuOMkwYa6-dv4UQdn4GKr6Ow',
    appId: '1:322047224635:android:16ac7d8a6518a95b',
    messagingSenderId: '322047224635',
    projectId: 'flutter-ui-challenges-hgl',
    databaseURL: 'https://flutter-ui-challenges-hgl.firebaseio.com',
    storageBucket: 'flutter-ui-challenges-hgl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzC3rYW7IaRhL9ZoAX7WjefJEEGQnlwVs',
    appId: '1:322047224635:ios:aa534f2a855aa0bdd2e51e',
    messagingSenderId: '322047224635',
    projectId: 'flutter-ui-challenges-hgl',
    databaseURL: 'https://flutter-ui-challenges-hgl.firebaseio.com',
    storageBucket: 'flutter-ui-challenges-hgl.appspot.com',
    androidClientId:
        '322047224635-9mqs8s0t8vgcn51njv59cudn2721feb2.apps.googleusercontent.com',
    iosClientId:
        '322047224635-dcrsla38nrue26isrvt3tnjrc2eleok3.apps.googleusercontent.com',
    iosBundleId: 'com.onemdev.flutter-ui-challenges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzC3rYW7IaRhL9ZoAX7WjefJEEGQnlwVs',
    appId: '1:322047224635:ios:99d72077bc2e6c0bd2e51e',
    messagingSenderId: '322047224635',
    projectId: 'flutter-ui-challenges-hgl',
    databaseURL: 'https://flutter-ui-challenges-hgl.firebaseio.com',
    storageBucket: 'flutter-ui-challenges-hgl.appspot.com',
    androidClientId:
        '322047224635-9mqs8s0t8vgcn51njv59cudn2721feb2.apps.googleusercontent.com',
    iosClientId:
        '322047224635-re8jqqobom6s24tjee2mejcijpo9jqba.apps.googleusercontent.com',
    iosBundleId: 'com.onemdev.flutter-ui-challenges-mac',
  );
}
