import 'ui_item.dart';
import 'ui_designer.dart';

List<UIItem> uilist = [
  new UIItem(
    id: 1,
    name: "Healthy Food Delivery",
    designer: "firdsm",
    // "designer": "designer",
    source: "dribbble",
    miniApp: "hfdHome",
    link: "https://dribbble.com/shots/6790111-Healthy-Food-Delivery",
    thumbnail: "assets/thumbnails/healthy_food_delivery.png",
    tabletSupport: true,
    landscapeSupport: true,
    webSupport: true,
    desktopSupport: true,
  ),
  new UIItem(
    id: 2,
    name: "Hot Air Balloon",
    designer: "designkes",
    // "designer": "designer",
    source: "dribbble",
    miniApp: "habHome",
    link: "https://designkes.live/designs/mobile/hot-air-balloon/",
    thumbnail: "assets/thumbnails/hot_air_balloon.jpg",
    tabletSupport: true,
    landscapeSupport: true,
  ),
  new UIItem(
    id: 3,
    name: "Sky View",
    designer: "designkes",
    // "designer": "designer",
    source: "dribbble",
    miniApp: "skHome",
    link: "https://designkes.live/designs/mobile/skyview-mars/",
    thumbnail: "assets/thumbnails/sky_view.jpg",
    tabletSupport: true,
    landscapeSupport: true,
  ),
  new UIItem(
    id: 4,
    name: "Asics Shoes concept",
    designer: "anonymous",
    // "designer": "designer",
    source: "youtube",
    miniApp: "ascHome",
    link: "https://www.youtube.com/watch?v=PYLHeRTNLWE",
    thumbnail: "assets/thumbnails/asics_shoes_concept.jpg",
    tabletSupport: true,
    landscapeSupport: true,
    webSupport: true,
    desktopSupport: true,
  ),
];

List<UIDesigner> designersList = [
  new UIDesigner(
    id: 1,
    username: "firdsm",
    name: "Mohammad Firdaus",
    description: null,
    job: null,
    location: null,
    facebook: "firdsm",
    twitter: null,
    instagram: "firdsm",
    linkedin: null,
    skype: null,
    dribbble: "firdsm",
    behance: "firdsm",
    website: null,
    fiverr: null,
    upwork: null,
    phone: [],
    emails: [],
  ),
  new UIDesigner(
    id: 2,
    username: "designkes",
    name: "Designkes",
    description: null,
    job: null,
    location: null,
    facebook: null,
    twitter: null,
    instagram: "designkes",
    linkedin: null,
    skype: null,
    dribbble: "designkes",
    behance: "designkes",
    website: null,
    fiverr: null,
    upwork: null,
    emails: [],
    phone: [],
  ),
];

// new UIDesigner(
//   id: 1,
//   username: "",
//   name: null,
//   description: null,
//   job: null,
//   location: null,
//   facebook: null,
//   twitter: null,
//   instagram: null,
//   linkedin: null,
//   skype: null,
//   dribbble: null,
//   behance: null,
//   website: null,
//   fiverr: null,
//   upwork: null,
//   emails: [],
//   phone: [],
// ),
