import 'ui_item.dart';
import 'ui_designer.dart';

List<UIItem> uilist = [
  new UIItem(
    id: 1,
    name: "Healthy Food Delivery",
    designer: "firdsm",
    // "designer": "designer",
    source: "dribbble",
    miniApp: "hfdHome",
    link: "https://dribbble.com/shots/6790111-Healthy-Food-Delivery",
    thumbnail: "assets/thumbnails/healthy_food_delivery.jpg",
    tabletSupport: true,
    landscapeSupport: true,
    webSupport: true,
    desktopSupport: true,
  ),
  new UIItem(
    id: 2,
    name: "Hot Air Balloon",
    designer: "designkes",
    // "designer": "designer",
    source: "dribbble",
    miniApp: "habHome",
    link: "https://designkes.live/designs/mobile/hot-air-balloon/",
    thumbnail: "assets/thumbnails/hot_air_balloon.jpg",
    tabletSupport: true,
    landscapeSupport: true,
  ),
  new UIItem(
    id: 3,
    name: "Sky View",
    designer: "designkes",
    // "designer": "designer",
    source: "dribbble",
    miniApp: "skHome",
    link: "https://designkes.live/designs/mobile/skyview-mars/",
    thumbnail: "assets/thumbnails/sky_view.jpg",
    tabletSupport: true,
    landscapeSupport: true,
    webSupport: true,
    desktopSupport: true,
  ),
  new UIItem(
    id: 4,
    name: "Asics Shoes concept",
    designer: "anonymous",
    // "designer": "designer",
    source: "youtube",
    miniApp: "ascHome",
    link: "https://www.youtube.com/watch?v=PYLHeRTNLWE",
    thumbnail: "assets/thumbnails/asics_shoes_concept.jpg",
    tabletSupport: true,
    landscapeSupport: true,
    webSupport: true,
    desktopSupport: true,
  ),
  new UIItem(
    id: 5,
    name: "Egg Timer Concept",
    designer: "ultranoir",
    description:
        "This UI was pirmarly built by fluttery youtube channel. But for some reasons all the resources published by him was removed from every online platform. Someone saved his video tutorials on google drive so I found those videos and build this one master piece with my code style",
    source: "dribbble",
    miniApp: "etcHome",
    link:
        "https://dribbble.com/shots/2764686-Original-timer-app-UX-interaction",
    thumbnail: "assets/thumbnails/egg_timer_concept.jpg",
    tabletSupport: true,
    landscapeSupport: true,
    webSupport: true,
    desktopSupport: true,
  ),
];

List<UIDesigner> designersList = [
  new UIDesigner(
    id: 1,
    username: "firdsm",
    name: "Mohammad Firdaus",
    description: null,
    job: null,
    location: null,
    facebook: "firdsm",
    twitter: null,
    instagram: "firdsm",
    linkedin: null,
    skype: null,
    dribbble: "firdsm",
    behance: "firdsm",
    website: null,
    fiverr: null,
    upwork: null,
    phone: [],
    emails: [],
  ),
  new UIDesigner(
    id: 2,
    username: "designkes",
    name: "Designkes",
    description: null,
    job: null,
    location: null,
    facebook: null,
    twitter: null,
    instagram: "designkes",
    linkedin: null,
    skype: null,
    dribbble: "designkes",
    behance: "designkes",
    website: null,
    fiverr: null,
    upwork: null,
    emails: [],
    phone: [],
  ),
  new UIDesigner(
    id: 3,
    username: "ultranoir",
    name: "Ultranoir",
    description: null,
    job: null,
    location: null,
    facebook: null,
    twitter: null,
    instagram: null,
    linkedin: null,
    skype: null,
    dribbble: "ultranoir",
    behance: null,
    website: "https://www.ultranoir.com/en/",
    fiverr: null,
    upwork: null,
    emails: ["hello@ultranoir.com"],
    phone: ["+33142714836"],
  ),
];
