on:
  push:
    tags:
      - "*"

name: Linux build and release
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: "3.24.5"
          channel: "stable"

      - uses: actions/checkout@v4
        with:
          path: "app"

      - name: Install required build tools for linux
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - run: |
          cd app
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release
          cd build/linux/x64/release
          zip -r linux-release.zip bundle

      - name: Create linux Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/linux/x64/release/linux-release.zip"
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
